// Icon Mappings - Replace emojis with Lucide React icons
import {
    MessageSquare,
    Palette,
    Zap,
    BookOpen,
    Video,
    Sparkles,
    Music,
    Scissors,
    BarChart3,
    Rocket,
    Camera,
    Lightbulb,
    CheckCircle2,
    XCircle,
    AlertTriangle,
    Upload,
    Download,
    Play,
    Pause,
    SkipForward,
    SkipBack,
    Volume2,
    VolumeX,
    Maximize,
    Minimize,
    Settings,
    Trash2,
    Edit3,
    Eye,
    EyeOff,
    Heart,
    Share2,
    Copy,
    Check,
    X,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    ChevronUp,
    MoreHorizontal,
    MoreVertical,
    Search,
    Filter,
    SortAsc,
    SortDesc,
    Calendar,
    Clock,
    User,
    Users,
    Mail,
    Phone,
    MapPin,
    Globe,
    Link2,
    ExternalLink,
    File,
    FileText,
    Folder,
    Image,
    Film,
    Mic,
    Speaker,
    Headphones,
    Smartphone,
    Monitor,
    Tablet,
    Laptop,
    Cpu,
    HardDrive,
    Wifi,
    WifiOff,
    Battery,
    BatteryCharging,
    Power,
    Loader2,
    RefreshCw,
    RotateCw,
    RotateCcw,
    ZoomIn,
    ZoomOut,
    Move,
    Crop,
    Sliders,
    Layers,
    Grid,
    Layout,
    Columns,
    Rows,
    Square,
    Circle,
    Triangle,
    Star,
    Award,
    TrendingUp,
    TrendingDown,
    Activity,
    PieChart,
    DollarSign,
    CreditCard,
    ShoppingCart,
    Package,
    Truck,
    Home,
    Building,
    Store,
    Briefcase,
    Bookmark,
    Tag,
    Hash,
    AtSign,
    Percent,
    Plus,
    Minus,
    Divide,
    Equal,
    Info,
    HelpCircle,
    AlertCircle,
    Bell,
    BellOff,
    Flag,
    Archive,
    Inbox,
    Send,
    Paperclip,
    Save,
    Lock,
    Unlock,
    Key,
    Shield,
    ShieldOff,
    Target,
    Crosshair,
    Navigation,
    Compass,
    Map,
    Sun,
    Moon,
    Cloud,
    CloudRain,
    CloudSnow,
    Wind,
    Droplet,
    Thermometer,
    Umbrella,
    Coffee,
    Gift,
    ShoppingBag,
    Smile,
    Frown,
    Meh,
    ThumbsUp,
    ThumbsDown,
    type LucideIcon,
} from 'lucide-react'

// Emoji to Icon mapping
export const iconMap = {
    // Communication
    '💬': MessageSquare,
    '📧': Mail,
    '📞': Phone,
    '📱': Smartphone,

    // Design & Creative
    '🎨': Palette,
    '✨': Sparkles,
    '🎬': Video,
    '📹': Camera,
    '🎥': Film,
    '🎵': Music,
    '🎧': Headphones,
    '🎤': Mic,

    // Actions
    '⚡': Zap,
    '🚀': Rocket,
    '✂️': Scissors,
    '✏️': Edit3,
    '🔍': Search,
    '🔗': Link2,
    '📎': Paperclip,
    '💾': Save,
    '🗑️': Trash2,

    // Status
    '✅': CheckCircle2,
    '❌': XCircle,
    '⚠️': AlertTriangle,
    '💡': Lightbulb,
    'ℹ️': Info,
    '❓': HelpCircle,
    '🔔': Bell,
    '🏆': Award,
    '⭐': Star,
    '❤️': Heart,
    '👍': ThumbsUp,
    '👎': ThumbsDown,

    // Learning & Content
    '📚': BookOpen,
    '📖': FileText,
    '📄': File,
    '📊': BarChart3,
    '📈': TrendingUp,
    '📉': TrendingDown,

    // Media Controls
    '▶️': Play,
    '⏸️': Pause,
    '⏭️': SkipForward,
    '⏮️': SkipBack,
    '🔊': Volume2,
    '🔇': VolumeX,

    // Navigation
    '🏠': Home,
    '🗂️': Folder,
    '📁': Folder,
    '🌐': Globe,
    '🧭': Compass,
    '🗺️': Map,

    // Time & Calendar
    '📅': Calendar,
    '⏰': Clock,

    // People
    '👤': User,
    '👥': Users,

    // Settings & Tools
    '⚙️': Settings,
    '🎚️': Sliders,
    '🔧': Settings,
    '🛠️': Settings,

    // Weather & Nature
    '☀️': Sun,
    '🌙': Moon,
    '☁️': Cloud,
    '🌧️': CloudRain,
    '❄️': CloudSnow,
    '💧': Droplet,

    // Business
    '💼': Briefcase,
    '🏢': Building,
    '🏪': Store,
    '💰': DollarSign,
    '💳': CreditCard,
    '🛒': ShoppingCart,
    '📦': Package,
    '🚚': Truck,

    // Misc
    '🎁': Gift,
    '☕': Coffee,
    '🔒': Lock,
    '🔓': Unlock,
    '🔑': Key,
    '🛡️': Shield,
    '🎯': Target,
    '🏁': Flag,
    '📌': MapPin,
    '🔖': Bookmark,
    '🏷️': Tag,
    '#️⃣': Hash,
    '@': AtSign,
    '%': Percent,
} as const

// Helper function to get icon component
export function getIcon(emoji: string): LucideIcon | null {
    return iconMap[emoji as keyof typeof iconMap] || null
}

// Commonly used icons (exported for convenience)
export const Icons = {
    // Actions
    Upload,
    Download,
    Edit: Edit3,
    Delete: Trash2,
    Save,
    Copy,
    Share: Share2,

    // Status
    Success: CheckCircle2,
    Error: XCircle,
    Warning: AlertTriangle,
    Info,
    Help: HelpCircle,

    // Navigation
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    ChevronUp,
    Menu: MoreHorizontal,

    // Media
    Play,
    Pause,
    Video,
    Camera,
    Music,

    // UI
    Close: X,
    Check,
    Plus,
    Minus,
    Search,
    Filter,
    Settings,

    // Loading
    Spinner: Loader2,
    Refresh: RefreshCw,

    // Creative
    Sparkles,
    Palette,
    Scissors,
    Zap,
    Rocket,

    // Content
    BookOpen,
    FileText,
    Folder,

    // Communication
    MessageSquare,
    Mail,
    Phone,

    // People
    User,
    Users,

    // Devices
    Smartphone,
    Mic,

    // Misc
    Eye,
    EyeOff,
    Heart,
    Star,
    Award,
    Lightbulb,
    Target,
    Flag,
    Calendar,
    Clock,
    Globe,
    Home,
    Briefcase,
    ShoppingCart,
    Package,
    Lock,
    Unlock,
    Shield,
    Bell,
    Bookmark,
    Tag,
    Link: Link2,
    ExternalLink,
    BarChart: BarChart3,
    TrendingUp,
    TrendingDown,
    Activity,
    Maximize,
    Minimize,
    ZoomIn,
    ZoomOut,
    Crop,
    Layers,
    Grid,
    Layout,
    Sun,
    Moon,
    Cloud,
    Droplet,
    Coffee,
    Gift,
    Smile,
    Frown,
    ThumbsUp,
    ThumbsDown,
} as const

export type IconName = keyof typeof Icons
